name: execute release actions
permissions:
  contents: write

on:
  push:
    branches:
    - "**"

jobs:
  get-changes:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    name: generate-changed-dir-matrix
    outputs:
      directories: ${{ steps.check-changes.outputs.directories }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - id: check-changes
      uses: frozengoats/github-actions/changes@changes-v1
      with:
        exclude: .git*
        must-contain: VERSION

  publish:
    needs: get-changes
    runs-on: ubuntu-24.04
    if: needs.get-changes.outputs.directories != '[]'
    strategy:
      matrix:
        item: ${{ fromJson(needs.get-changes.outputs.directories) }}
    steps:
    - name: display info
      run: |
        echo ${{ matrix.item.name }}
        echo ${{ matrix.item.path }}