name: execute release actions
permissions:
  contents: write
  checks: read

on:
  push:
    branches:
    - "**"

jobs:
  get-changes:
    runs-on: ubuntu-24.04
    name: generate-changed-dir-matrix
    outputs:
      directories: ${{ steps.check-changes.outputs.directories }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - id: check-changes
      uses: frozengoats/github-actions/changes@changes-v1
      with:
        exclude: .git*
        must-contain: VERSION

  publish:
    needs: get-changes
    runs-on: ubuntu-24.04
    if: needs.get-changes.outputs.directories != '[]'
    strategy:
      matrix:
        item: ${{ fromJson(needs.get-changes.outputs.directories) }}
    defaults:
      run:
        working-directory: ${{ matrix.item.path }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: get version
      id: version
      uses: frozengoats/github-actions/version@version-v1
      with:
        working-directory: ${{ matrix.item.path }}
    - name: build docker image
      run: VERSION=${{ steps.version.outputs.version-tag }} make -f ../Makefile build
    - name: tag major version of docker image
      run: VERSION=${{ steps.version.outputs.version-tag-major }} make -f ../Makefile build
    - name: login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - if: ${{ steps.version.outputs.on-parent-branch == 'true' }}
      name: publish container images
      run: make -f ../Makefile publish
    - uses: frozengoats/github-actions/release@release-v1
      with:
        tag-prefix: ${{ matrix.item.name }}-
        create-release: true
        create-version-tag: true
        create-major-version-tag: 'true'

  branch-protection-funnel:
    runs-on: ubuntu-24.04
    name: Verify integration tasks
    needs:
    - get-changes
    - publish
    steps:
    - name: Integration tasks succeeded
      if: ${{ !(contains(needs.*.result, 'failure')) }}
      run: exit 0
    - name: Integration tasks failed
      if: ${{ contains(needs.*.result, 'failure') }}
      run: exit 1
    - uses: frozengoats/github-actions/release@release-v1
      with:
        update-base-tag: true